language: objective-c
cache: bundle

before_script:
  - script/ci/travis/instruments-auth.sh

script:
  - bundle update
  - bundle exec rake spec

rvm:
  - 2.3.1

notifications:
  email:
    recipients:
      - joshuajmoody@gmail.com
    on_success: change
    on_failure: always
